In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Get Salex Lexicon

In [2]:
SALEX = pd.read_csv('salex_nrc.csv').set_index('term_str')
SALEX.columns = [col.replace('nrc_','') for col in SALEX.columns]
SALEX

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust,sentiment
term_str,,,,,,,,,,,
abandon,0,0,0,1,0,1,0,1,0,0,-1
abandoned,1,0,0,1,0,1,0,1,0,0,-1
abandonment,1,0,0,1,0,1,0,1,1,0,-1
abduction,0,0,0,1,0,1,0,1,1,0,-1
aberration,0,0,1,0,0,1,0,0,0,0,-1
...,...,...,...,...,...,...,...,...,...,...,...
young,0,1,0,0,1,0,1,0,1,0,1
youth,1,1,0,1,1,0,1,0,1,0,1
zeal,0,1,0,0,1,0,1,0,1,1,1
zealous,0,0,0,0,1,0,1,0,0,1,1
zest,0,1,0,0,1,0,1,0,0,1,1

## Reading in the LIB and Tokens table

In [3]:
LIB = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/LIB.csv', index_col='mag_id').sort_index()
TOKENS = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/CORPUS.csv', index_col=['mag_id','page_num','token_num']).sort_index()
TOKENS = TOKENS.join(LIB)
TOKENS.head()

                          pos pos_group token_str term_str       epub_id  \
mag_id page_num token_num
0      1        0          DT        DT       The      the  vo8DAAAAMBAJ
                1          NN        NN      text     text  vo8DAAAAMBAJ
                2          IN        IN        on       on  vo8DAAAAMBAJ
                3          DT        DT      this     this  vo8DAAAAMBAJ
                4          NN        NN      page     page  vo8DAAAAMBAJ

                                 date  \
mag_id page_num token_num
0      1        0          1972-12-07
                1          1972-12-07
                2          1972-12-07
                3          1972-12-07
                4          1972-12-07

                                                                       pages  \
mag_id page_num token_num
0      1        0          ["\n\n\n\nThis book was produced in EPUB forma...
                1          ["\n\n\n\nThis book was produced in EPUB forma...
                2          ["\n\n\n\nThis book was produced in EPUB forma...
                3          ["\n\n\n\nThis book was produced in EPUB forma...
                4          ["\n\n\n\nThis book was produced in EPUB forma...

                           month      quarter  page_num  \
mag_id page_num token_num
0      1        0             12  4th Quarter        68
                1             12  4th Quarter        68
                2             12  4th Quarter        68
                3             12  4th Quarter        68
                4             12  4th Quarter        68

                                                                       title  \
mag_id page_num token_num
0      1        0          What Dope Arrest is Doing to Career of Barbara...
                1          What Dope Arrest is Doing to Career of Barbara...
                2          What Dope Arrest is Doing to Career of Barbara...
                3          What Dope Arrest is Doing to Career of Barbara...
                4          What Dope Arrest is Doing to Career of Barbara...

                           character_len
mag_id page_num token_num
0      1        0                  99374
                1                  99374
                2                  99374
                3                  99374
                4                  99374

In [4]:
TOKENS.shape

(131948, 12)

In [5]:
TOKENS_SA = TOKENS.join(SALEX, on='term_str', how='left').fillna(0)
TOKENS_SA

                           pos pos_group token_str  term_str       epub_id  \
mag_id page_num token_num
0      1        0           DT        DT       The       the  vo8DAAAAMBAJ
                1           NN        NN      text      text  vo8DAAAAMBAJ
                2           IN        IN        on        on  vo8DAAAAMBAJ
                3           DT        DT      this      this  vo8DAAAAMBAJ
                4           NN        NN      page      page  vo8DAAAAMBAJ
...                        ...       ...       ...       ...           ...
9      68       55         NNP        NN      INC.       inc  mEEDAAAAMBAJ
                57         NNP        NN  Michigan  michigan  mEEDAAAAMBAJ
                58         NNP        NN    Avenue    avenue  mEEDAAAAMBAJ
                60         NNP        NN   Chicago   chicago  mEEDAAAAMBAJ
                62         NNP        NN  Illinois  illinois  mEEDAAAAMBAJ

                                 date  \
mag_id page_num token_num
0      1        0          1972-12-07
                1          1972-12-07
                2          1972-12-07
                3          1972-12-07
                4          1972-12-07
...                               ...
9      68       55         1959-04-09
                57         1959-04-09
                58         1959-04-09
                60         1959-04-09
                62         1959-04-09

                                                                       pages  \
mag_id page_num token_num
0      1        0          ["\n\n\n\nThis book was produced in EPUB forma...
                1          ["\n\n\n\nThis book was produced in EPUB forma...
                2          ["\n\n\n\nThis book was produced in EPUB forma...
                3          ["\n\n\n\nThis book was produced in EPUB forma...
                4          ["\n\n\n\nThis book was produced in EPUB forma...
...                                                                      ...
9      68       55         ["\n\n\n\nThis book was produced in EPUB forma...
                57         ["\n\n\n\nThis book was produced in EPUB forma...
                58         ["\n\n\n\nThis book was produced in EPUB forma...
                60         ["\n\n\n\nThis book was produced in EPUB forma...
                62         ["\n\n\n\nThis book was produced in EPUB forma...

                           month      quarter  page_num  ... anticipation  \
mag_id page_num token_num                                ...
0      1        0             12  4th Quarter        68  ...          0.0
                1             12  4th Quarter        68  ...          0.0
                2             12  4th Quarter        68  ...          0.0
                3             12  4th Quarter        68  ...          0.0
                4             12  4th Quarter        68  ...          0.0
...                          ...          ...       ...  ...          ...
9      68       55             4  2nd Quarter        68  ...          0.0
                57             4  2nd Quarter        68  ...          0.0
                58             4  2nd Quarter        68  ...          0.0
                60             4  2nd Quarter        68  ...          0.0
                62             4  2nd Quarter        68  ...          0.0

                           disgust  fear  joy  negative  positive  sadness  \
mag_id page_num token_num
0      1        0              0.0   0.0  0.0       0.0       0.0      0.0
                1              0.0   0.0  0.0       0.0       0.0      0.0
                2              0.0   0.0  0.0       0.0       0.0      0.0
                3              0.0   0.0  0.0       0.0       0.0      0.0
                4              0.0   0.0  0.0       0.0       0.0      0.0
...                            ...   ...  ...       ...       ...      ...
9      68       55             0.0   0.0  0.0       0.0       0.0      0.0
                57             0.0   0.0  0.0       0.0       0.0      0.0
                58             0.0   0.0  0.0       0.0       0.0      0.0
                60             0.0   0.0  0.0       0.0       0.0      0.0
                62             0.0   0.0  0.0       0.0       0.0      0.0

                           surprise  trust  sentiment
mag_id page_num token_num
0      1        0               0.0    0.0        0.0
                1               0.0    0.0        0.0
                2               0.0    0.0        0.0
                3               0.0    0.0        0.0
                4               0.0    0.0        0.0
...                             ...    ...        ...
9      68       55              0.0    0.0        0.0
                57              0.0    0.0        0.0
                58              0.0    0.0        0.0
                60              0.0    0.0        0.0
                62              0.0    0.0        0.0

[131948 rows x 23 columns]

In [6]:
# going to calculate the overall sentiment 
emo_cols = "anger anticipation disgust fear joy sadness surprise trust sentiment".split()
TOKENS_SA['overall_sent'] = TOKENS_SA[emo_cols].sum(1)
TOKENS_SA

                           pos pos_group token_str  term_str       epub_id  \
mag_id page_num token_num
0      1        0           DT        DT       The       the  vo8DAAAAMBAJ
                1           NN        NN      text      text  vo8DAAAAMBAJ
                2           IN        IN        on        on  vo8DAAAAMBAJ
                3           DT        DT      this      this  vo8DAAAAMBAJ
                4           NN        NN      page      page  vo8DAAAAMBAJ
...                        ...       ...       ...       ...           ...
9      68       55         NNP        NN      INC.       inc  mEEDAAAAMBAJ
                57         NNP        NN  Michigan  michigan  mEEDAAAAMBAJ
                58         NNP        NN    Avenue    avenue  mEEDAAAAMBAJ
                60         NNP        NN   Chicago   chicago  mEEDAAAAMBAJ
                62         NNP        NN  Illinois  illinois  mEEDAAAAMBAJ

                                 date  \
mag_id page_num token_num
0      1        0          1972-12-07
                1          1972-12-07
                2          1972-12-07
                3          1972-12-07
                4          1972-12-07
...                               ...
9      68       55         1959-04-09
                57         1959-04-09
                58         1959-04-09
                60         1959-04-09
                62         1959-04-09

                                                                       pages  \
mag_id page_num token_num
0      1        0          ["\n\n\n\nThis book was produced in EPUB forma...
                1          ["\n\n\n\nThis book was produced in EPUB forma...
                2          ["\n\n\n\nThis book was produced in EPUB forma...
                3          ["\n\n\n\nThis book was produced in EPUB forma...
                4          ["\n\n\n\nThis book was produced in EPUB forma...
...                                                                      ...
9      68       55         ["\n\n\n\nThis book was produced in EPUB forma...
                57         ["\n\n\n\nThis book was produced in EPUB forma...
                58         ["\n\n\n\nThis book was produced in EPUB forma...
                60         ["\n\n\n\nThis book was produced in EPUB forma...
                62         ["\n\n\n\nThis book was produced in EPUB forma...

                           month      quarter  page_num  ... disgust  fear  \
mag_id page_num token_num                                ...
0      1        0             12  4th Quarter        68  ...     0.0   0.0
                1             12  4th Quarter        68  ...     0.0   0.0
                2             12  4th Quarter        68  ...     0.0   0.0
                3             12  4th Quarter        68  ...     0.0   0.0
                4             12  4th Quarter        68  ...     0.0   0.0
...                          ...          ...       ...  ...     ...   ...
9      68       55             4  2nd Quarter        68  ...     0.0   0.0
                57             4  2nd Quarter        68  ...     0.0   0.0
                58             4  2nd Quarter        68  ...     0.0   0.0
                60             4  2nd Quarter        68  ...     0.0   0.0
                62             4  2nd Quarter        68  ...     0.0   0.0

                           joy  negative  positive  sadness  surprise  trust  \
mag_id page_num token_num
0      1        0          0.0       0.0       0.0      0.0       0.0    0.0
                1          0.0       0.0       0.0      0.0       0.0    0.0
                2          0.0       0.0       0.0      0.0       0.0    0.0
                3          0.0       0.0       0.0      0.0       0.0    0.0
                4          0.0       0.0       0.0      0.0       0.0    0.0
...                        ...       ...       ...      ...       ...    ...
9      68       55         0.0       0.0       0.0      0.0       0.0    0.0
                57         0.0       0.0       0.0      0.0       0.0    0.0
                58         0.0       0.0       0.0      0.0       0.0    0.0
                60         0.0       0.0       0.0      0.0       0.0    0.0
                62         0.0       0.0       0.0      0.0       0.0    0.0

                           sentiment  overall_sent
mag_id page_num token_num
0      1        0                0.0           0.0
                1                0.0           0.0
                2                0.0           0.0
                3                0.0           0.0
                4                0.0           0.0
...                              ...           ...
9      68       55               0.0           0.0
                57               0.0           0.0
                58               0.0           0.0
                60               0.0           0.0
                62               0.0           0.0

[131948 rows x 24 columns]

# Vocab_sent
- Sentiment values associated with a subset of the VOCAB from a curated sentiment lexicon.

In [7]:
VOCAB = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/VOCAB.csv',index_col='term_str')
VOCAB

,n,n_chars,p,i,max_pos,max_pos_group,stop,stem_porter
term_str,,,,,,,,
aa,2,2,0.000015,16.009610,NNP,NN,0,aa
aaf,1,3,0.000008,17.009610,NNP,NN,0,aaf
aaron,11,5,0.000083,13.550178,NNP,NN,0,aaron
ababa,1,5,0.000008,17.009610,NNP,NN,0,ababa
abandoned,2,9,0.000015,16.009610,VBN,VB,0,abandon
...,...,...,...,...,...,...,...,...
zumwalt,1,7,0.000008,17.009610,NNP,NN,0,zumwalt
zunicia,1,7,0.000008,17.009610,NNP,NN,0,zunicia
zuniga,2,6,0.000015,16.009610,NNP,NN,0,zuniga
zurich,5,6,0.000038,14.687682,NNP,NN,0,zurich
zw,1,2,0.000008,17.009610,NN,NN,0,zw

In [8]:
term_sent_map = (
    TOKENS_SA[['term_str', 'overall_sent']]
    .value_counts()
    .unstack(fill_value=0)
    .idxmax(axis=1)
)
term_sent_map

term_str
aa           0.0
aaf          0.0
aaron        0.0
ababa        0.0
abandoned    2.0
            ...
zumwalt      0.0
zunicia      0.0
zuniga       0.0
zurich       0.0
zw           0.0
Length: 16287, dtype: float64

In [13]:
VOCAB['overall_sent'] = VOCAB.index.map(term_sent_map)
VOCAB.sample(15)

,n,n_chars,p,i,max_pos,max_pos_group,stop,stem_porter,overall_sent
term_str,,,,,,,,,
juice,4,5,0.000030,15.009610,NN,NN,0,juic,0.0
thomas,58,6,0.000440,11.151629,NNP,NN,0,thoma,0.0
pride,9,5,0.000068,13.839685,NN,NN,0,pride,2.0
stapleton,1,9,0.000008,17.009610,NNP,NN,0,stapleton,0.0
lauderdale,2,10,0.000015,16.009610,NNP,NN,0,lauderdal,0.0
rutgers,1,7,0.000008,17.009610,NNP,NN,0,rutger,0.0
commanding,2,10,0.000015,16.009610,VBG,VB,0,command,2.0
irsmemoned,1,10,0.000008,17.009610,NN,NN,0,irsmemon,0.0
clowns,1,6,0.000008,17.009610,NNP,NN,0,clown,0.0
tiddle,2,6,0.000015,16.009610,NNP,NN,0,tiddl,0.0
lawd,1,4,0.000008,17.009610,NNP,NN,0,lawd,0.0
t,1,1,0.000008,17.009610,CC,CC,1,t,0.0
pros,2,4,0.000015,16.009610,NNS,NN,0,pro,0.0
shelby,2,6,0.000015,16.009610,NNP,NN,0,shelbi,0.0
implied,1,7,0.000008,17.009610,VBN,VB,0,impli,0.0

In [ ]:
# saving vocab_sent 
# VOCAB.to_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/SA/VOCAB_SENT.csv')

# BOW SENT

In [16]:
BOW = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/BOW.csv',index_col=['mag_id','term_str'])
BOW

                    n     tfidf
mag_id term_str
0      abandonment  1  3.321928
       abc          1  1.000000
       abctv        4  0.747494
       ability      3  2.000000
       able         4  1.711181
...                ..       ...
9      zanzi        1  3.321928
       zealand      1  3.321928
       zion         1  1.321928
       zone         2  2.095206
       zurich       1  1.321928

[39538 rows x 2 columns]

In [30]:
BOW.index.get_level_values('term_str')

Index(['abandonment', 'abc', 'abctv', 'ability', 'able', 'about', 'abroad',
       'absolutely', 'abuse', 'academic',
       ...
       'youths', 'yovm', 'yvette', 'yvon', 'yvonne', 'zanzi', 'zealand',
       'zion', 'zone', 'zurich'],
      dtype='object', name='term_str', length=39538)

In [35]:
BOW['overall_sent'] = BOW.index.get_level_values('term_str').map(term_sent_map)
BOW.sample(15)

                    n     tfidf  overall_sent
mag_id term_str
6      reed         1  1.321928           0.0
       located      1  1.000000           0.0
7      firing       1  0.736966           0.0
5      yet          3  0.643856           0.0
8      needy        1  2.321928           0.0
3      phased       1  3.321928           0.0
8      babies       1  1.736966           0.0
1      placards     2  5.265131           0.0
9      heroin       1  1.736966           0.0
0      music        2  0.000000           3.0
3      mother       6  0.000000           4.0
4      lets         1  1.736966           0.0
9      granted      1  0.736966           0.0
7      switzerland  1  0.736966           0.0
5      tobacco      3  2.643856           0.0

In [ ]:
BOW.to_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/SA/BOW_SENT.csv')

# DOC_SENT
- Computed sentiment per bag computed from BOW_SENT.

In [39]:
BOW

                    n     tfidf  overall_sent
mag_id term_str
0      abandonment  1  3.321928           3.0
       abc          1  1.000000           0.0
       abctv        4  0.747494           0.0
       ability      3  2.000000           0.0
       able         4  1.711181           0.0
...                ..       ...           ...
9      zanzi        1  3.321928           0.0
       zealand      1  3.321928           0.0
       zion         1  1.321928           0.0
       zone         2  2.095206           0.0
       zurich       1  1.321928           0.0

[39538 rows x 3 columns]

In [ ]:
DOC_SENT = BOW.copy()

DOC_SENT['weighted_sent'] = DOC_SENT['n'] * DOC_SENT['overall_sent']

sent_per_doc = (
    DOC_SENT.groupby(level='mag_id')['weighted_sent'].sum() /
    DOC_SENT.groupby(level='mag_id')['n'].sum()
)
sent_per_doc

                    n     tfidf  overall_sent  weighted_sent
mag_id term_str
0      abandonment  1  3.321928           3.0            3.0
       abc          1  1.000000           0.0            0.0
       abctv        4  0.747494           0.0            0.0
       ability      3  2.000000           0.0            0.0
       able         4  1.711181           0.0            0.0
...                ..       ...           ...            ...
9      zanzi        1  3.321928           0.0            0.0
       zealand      1  3.321928           0.0            0.0
       zion         1  1.321928           0.0            0.0
       zone         2  2.095206           0.0            0.0
       zurich       1  1.321928           0.0            0.0

[39538 rows x 4 columns]